### ISSUE TITLE
Editors are loaded in reverse

### ISSUE THREAD

**Issue by user72356** [ctf0/vscode-save-editor-layout#5]
- I have a layout with a horizontal split/vertical orientation (a top part and a bottom part).

![image](https://user-images.githubusercontent.com/45011262/152836927-e8ca0c8b-746d-4696-b2c3-b77503993c63.png)

- I save the layout, change the layout to "vertical orientation" and close all editors.
- **Now I open the group again and all of my editors are opened in the inverse order as compared to what was saved, and also as compared to what is shown in the settings file.**

![image](https://user-images.githubusercontent.com/45011262/152837106-3ed2f5e1-0c90-42f6-86d3-aa8cf45a5b6f.png)

![image](https://user-images.githubusercontent.com/45011262/152837063-c7fd8ec7-0756-4db3-a6ec-1bc40ed3bf4c.png)

- The up arrow, that would allow me to reorder the editors, don't seem to be present. The down arrow is, but doesn't do anything.

Thank you for your attention!

**Comment by ctf0** [comment]
> all of my editors are opened in the inverse order

not sure why this happend, will need to investigate.

> The up arrow, that would allow me to reorder the editors, don't seem to be present.

the up & left arrows are removed because of the editor limitations so they were actually working in some cases only.

> The down arrow is, but doesn't do anything.

they are suppose to update each item position, u can check the json file for the changes made when u click any arrow, also check https://github.com/ctf0/vscode-save-editor-layout/blob/master/CHANGELOG.md#021

**Comment by user72356** [comment]
Any updates on this?

**Comment by ctf0** [comment]
sorry, didnt have the time to work on it yet

**Comment by ctf0** [comment]
plz retest with the latest release

**Comment by user72356** [comment]
Yes working great now! Thank you for fixing.
